services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpx_webserver
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - gpx_sqlite_data:/var/www/html/db
    working_dir: /var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped

volumes:
  gpx_sqlite_data:
