services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpx_webserver
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped
