services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpx_webserver
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - PHP_UPLOAD_MAX_FILESIZE=10M
      - PHP_POST_MAX_SIZE=10M
    restart: unless-stopped
